use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let crate_path = PathBuf::from(&crate_dir);

    // Generate Rust bindings for C++
    cbindgen::Builder::new()
        .with_crate(&crate_path)
        .with_header("/* WARNING: This file is automatically generated by cbindgen. Do not modify manually! */")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(crate_path.join("include/rust_to_cpp.h"));


    // rust to cpp
    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=src/to_cpp.rs");
    println!("cargo:rerun-if-changed=src/call_cpp.rs");
}
