use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let crate_path = PathBuf::from(&crate_dir);

    // Generate Rust to C++ binding headers
    cbindgen::Builder::new()
        .with_crate(&crate_path)
        .with_header("/* WARNING: This file is automatically generated by cbindgen. Do not modify manually! */\n#pragma once")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(crate_path.join("include/rust_to_cpp.h"));

    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=src/rust_to_cpp.rs");
    println!("cargo:rerun-if-changed=src/call_cpp.rs");

    // C++ to Rust
    cxx_build::bridge("src/call_cpp.rs")
        .file("src/cpp/to_rust.cpp")
        .include("include")
        .std("c++17")
        .compile("cpp-to-rust");

    println!("cargo:rerun-if-changed=src/cpp/to_rust.cpp");
    println!("cargo:rerun-if-changed=include/cpp_to_rust.h");
}
