[package]
name = "rust-ffi"
version = "0.1.0"
edition = "2024"


[lib]
crate-type = ["rlib", "cdylib"]


[build-dependencies]
cbindgen = "0.29.0"
cxx-build = "1.0.183"

[dependencies]
cxx = "1.0.183"
