/* WARNING: This file is automatically generated by cbindgen. Do not modify manually! */
#pragma once

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

extern "C" {

void say_hello();

int32_t add(int32_t a, int32_t b);

void call_inner_function();

}  // extern "C"
